# docker-compose.production.yml

volumes:
  pg_data_production:
  static_volume:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,delayemtaski.freedynamicdns.net,51.250.103.119
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: aleksandr123444/taski_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/app/static/
  frontend:
    image: aleksandr123444/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: "npx serve -s /app/build -l 8000"
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: aleksandr123444/taski_gateway  # Качаем с Docker Hubub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80